apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kepler
  labels:
    project-template: global
spec:
  destinations:
    - namespace: 'kepler-edge'
      server: 'https://api.odh-cl1.apps.os-climate.org:6443'
  sourceRepos:
    - '*'
  roles:
    - name: project-admin
      description: Read/Write access to this project only
      policies:
        - p, proj:kepler:project-admin, applications, *, os-climate/kepler-osc, allow
        - p, proj:kepler:project-admin, applications, *, kepler/kepler-edge-demo-osc, allow
      groups:
        - kepler-admins
  namespaceResourceWhitelist:
    - group: ""
      kind: Node
    - group: kafka.strimzi.io
      kind: Kafka
    - group: kafka.strimzi.io
      kind: KafkaBridge
    - group: kafka.strimzi.io
      kind: KafkaConnect
    - group: kafka.strimzi.io
      kind: KafkaConnectS2I
    - group: kafka.strimzi.io
      kind: KafkaConnector
    - group: kafka.strimzi.io
      kind: KafkaMirrorMaker
    - group: kafka.strimzi.io
      kind: KafkaMirrorMaker2
    - group: kafka.strimzi.io
      kind: KafkaRebalance
    - group: kafka.strimzi.io
      kind: KafkaTopic
