apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gohan-cluster-secret
spec:
  secretStoreRef:
    name: opf-vault-store
    kind: SecretStore
  target:
    name: gohan-cluster-secret
    template:
      engineVersion: v2
      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster
        annotations:
          managed-by: argocd.argoproj.io
  dataFrom:
    - extract:
        key: moc/infra/argocd/gohan-cluster-secret
