apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kepler-edge-demo.yaml
patches:
  - patch: |
      - op: replace
        path: /spec/project
        value: kepler
    target:
      group: argoproj.io
      kind: Application
